package main

import (
	"fmt"
	"os"

	"github.com/dave/jennifer/jen"
	"github.com/june-style/go-sample/interface/logs"
)

func main() {
	logs.Info().Msg("Start generate by tools/generators/jen")

	args, err := NewArgs()
	if err != nil {
		logs.Fatal().SetError(err).Msg("Stopped")
	}

	logs.Info().Msg(fmt.Sprintf("File path: '%s'", args.FullPath()))

	buff, err := os.Create(args.FullPath())
	if err != nil {
		logs.Fatal().SetError(err).Msg("Stopped")
	}
	defer buff.Close()

	f := jen.NewFile(args.PackageName())
	f.HeaderComment("Code generated by tools/generators/jen. DO NOT EDIT.")

	f.Func().Id(args.MethodName()).Params().Block(
		jen.Qual("fmt", "Println").Call(jen.Lit("Hello, world!!")),
	)

	if err := f.Render(buff); err != nil {
		logs.Fatal().SetError(err).Msg("Stopped")
	}

	logs.Info().Msg("...done!")
}
