services:
  go-development:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ./:/go/src/github.com/june-style/go-sample:default
    networks:
      - internal
      - external
    tty: true

  local-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/go/src/github.com/june-style/go-sample:default
    networks:
      - internal
      - external
    depends_on:
      - redis
      - localstack

  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    env_file:
      - ./.env
    volumes:
      - ${REDIS_VOLUME_DIR:-./.volumes/redis}:/data:default
    networks:
      - internal
    command: redis-server --appendonly yes

  localstack:
    image: localstack/localstack:latest
    ports:
      - 127.0.0.1:4566:4566
    environment:
      - SERVICES=dynamodb,sqs
      - PERSISTENCE=1
    env_file:
      - ./.env
    volumes:
      - ${LOCALSTACK_VOLUME_DIR:-./.volumes/localstack}:/var/lib/localstack:default
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 127.0.0.1:5540:5540
    env_file:
      - ./.env
    volumes:
      - ${REDIS_VOLUME_DIR:-./.volumes/redisinsight}:/data:default
    networks:
      - internal
      - external
    depends_on:
      - redis

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - 127.0.0.1:8001:8001
    environment:
      - DYNAMO_ENDPOINT=${AWS_ENDPOINT-localstack:4566}
      - PORT=8001
      - AWS_REGION=${AWS_DEFAULT_REGION-ap-northeast-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-fake_access_key}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-fake_secret_access_key}
    env_file:
      - ./.env
    networks:
      - internal
      - external
    depends_on:
      - localstack

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
    internal: false
